### ISSUE TITLE
"Standing_Repair" "Kneel_Repair" "Prone_Repair" animations.

### ISSUE THREAD

**Issue by Kriegsler** [oOKexOo/AresModAchillesExpansion#10]
Those animations are looped. The NPC does the animations,then the animation stops (if it'd only be played once the NPC could then move) and starts it again. After the animation ends,the NPC goes slightly back. Say you put an ambient AI to "repair" a broken MRAP,he'd do it,and after 30 minutes,you'll find him 50 meters away from the location he's supposed to be in.

This doesn't happen with the prone_repair animation. HOWEVER. This animation stops at a certain moment. The AI is in the same position,his hands just don't move. (Don't prioritize fixing this. It's not that annoying.)

**Comment by oOKexOo** [comment]
Regarding to the kneel repair animation:
The current only way I can think of how to fix that issue is to use the "attach to" module in addition.
Since it is essential that you can move AI even if they are performing an animation, I won't include attach to in the animation function.
The drift you observe is actually an issue with the animation that should be reported to BIS.

**Comment by CreepPork** [comment]
Closed as this is a BI's issue.
