### ISSUE TITLE
Countermessure keybinding conflicts with zeus search bar.

### ISSUE THREAD

**Issue by Zakant** [oOKexOo/AresModAchillesExpansion#18]
On the latest **dev branch** their is a search bar for assets. When pressing `c` while typing in that search bar, achilles provides the message that no countermessures are available or fire countermessures. 
This problem only appears on the **dev branch** because the search bar is not implemented in the stable branch.

**Comment by oOKexOo** [comment]
Thank you. It is nice to have reports from dev branch. I will fix this bug. I'm glad they finally introduce a search bar.

**Comment by oOKexOo** [comment]
Should be fixed in Alpha 0.0.3.

**Comment by Zakant** [comment]
The fix is only working partially. If you type `c` into search bar no error message is shown. However, if you have a tank / plane selected it _will_ fire its countermessures even if you are typing into the search bar.

**Comment by oOKexOo** [comment]
I think it is fine for now. As soon as the search bar is introduced in the stable branch, I will fix it.
I don't work in the dev branch, so I currently can't look up for the required control id.

**Comment by oOKexOo** [comment]
Thank you for trying to fix the problem. I replaced the display event handler by the  control event handler attached to the mouse area as you did. The issue should be solved completely by 0.0.4.
I'm aware that the "keyDown" event handler also returns the status of ctrl and shift, but the Ares_Ctrl_Key_Pressed and Ares_Shift_Key_Pressed variables are essential, since they are needed in some curator event handlers.

**Comment by oOKexOo** [comment]
The mouse area control solution is flawed in the way that "CTRL + C/V" combinations are not detected by the "keyDown" control event handler. Hence, deep copy key combinations "SHIFT + CTRL + C/V" would no longer work. Therefore, I decided to go back to the display event handler solution.

**Comment by oOKexOo** [comment]
Don't know why this is still open.
