### ISSUE TITLE
Modules aren't loaded in version 0.0.3c

### ISSUE THREAD

**Issue by Zakant** [oOKexOo/AresModAchillesExpansion#19]
After the update of Achilles to 0.0.3c the modules aren't loaded correctly. If i switch to modules in the zeus view they are shown very short ( < 1 secound) and then disappear. Only the bis modules remain in the list. [The .rpt of the mission](https://github.com/oOKexOo/AresModAchillesExpansion/files/441235/arma3_2016-08-28_18-37-14.rpt.txt) start is linked, but i haven't seen anything special.
My game runs with a couple of mods but nothing THAT extraordinary that _should_ cause such and issue.
Greetings.

Edit: Not module related stuff such as deep copy are still working fine. The modules also show in the function viewer. I guess their is a problem updating the module tree view...

Edit2: I've investigated that issue a little further and it turns out that:
a) The modules under the `ACE` category _are_ available.
and 
b) that once i remote control a unit and go back into the curator interface the modules are _back_.
So im quite sure that at mission start something (other mod? arma itself?) overwrittes the custom module categories. Possible solution might be to add a keyboard shortcut to force a module reload. Not a nice solution but a working one for those people who have the problem...

**Comment by oOKexOo** [comment]
The command addCuratorAddons is used in the init in 0.0.3, which fixes several issues. Unfortunatelly, this command also removes the modules from the module tree. As you noticed, the only way to get them back is to reload the interface. The reload is done by script in the initphase, but for some reasons it happends before the effect of the addCuratorAddons occure in your case. Therefore, I have to improve the waitUntil conditions in order to fix it. I may upload a test version for you as soon as I improved it.

**Comment by oOKexOo** [comment]
Should be fixed in 0.0.4!

**Comment by oOKexOo** [comment]
Don't know why this was still open...
