### ISSUE TITLE
Error at Game Launch from Pw6 (v0.0.3)alpha

### ISSUE THREAD

**Issue by JHill29th** [oOKexOo/AresModAchillesExpansion#20]
This error is displayed when the game is launched with Ares Achillies.
`Script \achilles\modules_f_ares\Behaviours\functions\fn_BehaviourLandHelicopter.sqf not found`

Cannot connect to the server.

It looks like most of the sub-folders of the `addons` folder are empty...

**Comment by 50KAL0V** [comment]
Getting the same issue with the Armaholic version and the latest GitHub release

**Comment by oOKexOo** [comment]
I just downloaded the GitHub release myself and I had no problems... (https://github.com/oOKexOo/AresModAchillesExpansion/archive/Alpha-003.zip) 
I need more details:
The *.RTP log file located in "C:\user\<user name>\AppData\Local\Arma 3" would probably help me.

**Comment by 50KAL0V** [comment]
it turns out by launching your entire mod folder it runs fine, but if you use your own mod folder and put the .pbos in it (For example our community mod pack) it will fail with these errors.

` 9:34:38 Warning Message: Script \achilles\modules_f_ares\Behaviours\functions\fn_BehaviourLandHelicopter.sqf not found
 9:34:38 Warning Message: Script \achilles\modules_f_ares\Behaviours\functions\fn_SurrenderUnits.sqf not found
 9:34:38 Warning Message: Script \achilles\modules_f_ares\DevTools\functions\fn_DevTools_manageAdvancedCompositions.sqf not found
 9:34:38 Warning Message: Script \achilles\modules_f_ares\Spawn\functions\fn_SpawnEffect.sqf not found
 9:34:38 Warning Message: Script \achilles\modules_f_ares\Spawn\functions\fn_SpawnCreateEditIntel.sqf not found
 9:34:38 Warning Message: Script \achilles\modules_f_ares\Spawn\functions\fn_SpawnAdvancedCompositions.sqf not found
 9:34:38 Warning Message: Script \achilles\modules_f_ares\Spawn\functions\fn_SpawnExplosives.sqf not found`


Looks like its a prefix issue maybe?

**Comment by oOKexOo** [comment]
Wait a minute... do you try to run Ares and Achilles at the same time? They are not compatible with each other. The never were in the first place, since all functionalities from Ares are already present in Achilles.

**Comment by Trol1025** [comment]
I have same problem. Running game by PW6 only CBA and achilles. And same bug.
pw6 setings : https://gyazo.com/4cfaac594f075d069472a052556cdb08

**Comment by JHill29th** [comment]
>do you try to run Ares and Achilles at the same time?

No.
This is only an issue if downloading v0.0.3 from Play with Six.

**Comment by oOKexOo** [comment]
I was informed that the PW6 team fixed the issue. Please make sure you get v0.0.3.2.

**Comment by Trol1025** [comment]
Fixed

**Comment by JHill29th** [comment]
Well, I downloaded from Pw6 again (v0..3.2) and it doesn't look the same as when downloaded from your direct link.  Details below.

Parent Directory
<img src="https://puu.sh/qVqUB/bb991d3f3a.png">

Addons Folder
<img src="http://puu.sh/qVqWy/e1f4197ea6.png">

All subfolders within the addons folder are empty (and probably aren't supposed to be there anyway).
All `.bisign` files are created by a Pw6 key (`six_ares_mod_achilles_expansion.bikey`) located in the keys folder.  Your key isn't even there.

**Comment by oOKexOo** [comment]
WTF? I don't know how PW6 is handled, but I'm sure it is not intended to be that way. 
The empty folders are no probelem, since there was only the source code located which is not needed.
However, the different key makes no sense to me and will prevent you from connecting to servers with key restrictions. The only official key is achilles_0.0.3.bikey! 
Thank you for the screenshots. I will try to contact the PW6 team to fix it once and for all.

**Comment by oOKexOo** [comment]
I was informed that *.pbo signing by PW6 is a standard procedure.
The particular topic is closed, since the reported problem is fixed in PW6 version 0.0.3.2.
If you have any problems with the PW6 version, please create a new issue report.
