### ISSUE TITLE
can you add "copy to/ paste from clipboard" functions  from Ares 1.7.0?

### ISSUE THREAD

**Issue by unhappytroll** [oOKexOo/AresModAchillesExpansion#21]
Because "Save mission as SQF" isn't very useful if I want to save not a full mission but some assets only. And adding assets created in Eden isn't very easy.

**Comment by oOKexOo** [comment]
I won't include that function, since I'm developing a completely new system for saving assets/missions. The new system will save a wide range of attributes (e.g. ambient animations, loadouts, etc.). 
If your asset conists of static objects only, you can already save it as an advanced composition instead.

**Comment by unhappytroll** [comment]
Mmmm, did not think of that, thank you.

**Comment by unhappytroll** [comment]
Mmmm, did not think of that, thank you.

**Comment by unhappytroll** [comment]
Mmmm, did not think of that, thank you.

**Comment by unhappytroll** [comment]
Mmmm, did not think of that, thank you.

**Comment by unhappytroll** [comment]
Mmmm, did not think of that, thank you.
