### ISSUE TITLE
Placing modules (in Zeus)

### ISSUE THREAD

**Issue by CrazymanNL** [oOKexOo/AresModAchillesExpansion#25]
I have an Ares related bug, I have to place modules 10 times or more on a unit for that module to work.The mod is really fun and useful when it works but it is bugged most of the time. I have the mod installed on my server and its really annoying trying to get things done quickly in Zeus when I have to spend so much time trying to get the modules to work. Is this a known bug or is it just something I am doing wrong, I really enjoy the mod and so do the players on my server when it works but when it does'nt work I get frustrated. Thank for your time and please respond as soon as possible.

Best Regards,
Mason

**Comment by oOKexOo** [comment]
As I earlier mentioned this issue is not reproducible for me.
Some additional informations would help me a lot.

Common report procedure:

~~1) Topic~~
2) All add-ons that were running (include version)
3) Language Settings
4) Environment (e.g. client on dedicated server / client on hosted server /server host/ SP)
5) Reproducibility (e.g. always)
6) Report step by step how the issue can be reproduced (just an example; can also be a video)
7) Additonal Notes
 
Here is just an arbitrary example:
 
1) Cannot spawn smoke grenade with Effect Module
2) Achilles (0.0.2c); CBA (3.0.0); RHS (0.4.1.1)
3) English
4) Client on dedicated server
5) Happends only if RHS is activated
6.1) Set up a dedicated server with TADST running Tanoa Game Master
6.2) Join server and take Game Master slot
6.3) Place Effect Module and select smoke grenade
7) No script error was displayed

**Comment by CrazymanNL** [comment]
2) ares Achilles (0.03);CBA_A3(v3.1.1);RHS (0.4.1.1); Arma Enhanced Movement;Advanced urban rappling; All the NiArms;Task force Radio; Post apocalyptic music;advanced towing
3) English
4)client on hosted server
5) I don't know
6.1)start server
6.2)Join server and game master slot
6.3) placing a module noting happends
7) Only icon of the module is displayed but no menu pop up

**Comment by oOKexOo** [comment]
I don't have all of those mods.
Can you give it a try with Achilles, CBA ,RHS, Enhanced Movement, Advanced Rappling and TFR?
Just wondering if this combination also works for you as it does for me.

**Comment by Nels0** [comment]
I have had this issue also, on long operations.
Mods: ACE3, TFAR, CUP Terrains, Enhanced Movement, Advanced Rappelling/towing/sling loading, RHS AFRF/USAF/GREF
English
Tanoa
Dedicated Server
Common (i.e by the end of a 2-hour, 40man op the garrison functions etc may not work)
Notes: may be an issue with events on the server, or heavy network traffic?

**Comment by oOKexOo** [comment]
It is hard to predict what the origin of the problem is. The garrison function is executed local on the Zeus player. Hence, heavy network traffic should not have an influence. Were the units you wanted to apply the module placed by you as Zeus?

**Comment by oOKexOo** [comment]
If this problem is still present, please reopen the topic.
