### ISSUE TITLE
[Feature Request] Is there a way to automatically add objects that is not in the BI objects list?

### ISSUE THREAD

**Issue by unhappytroll** [oOKexOo/AresModAchillesExpansion#73]
For example, Land_Flush_Light_yellow_F, Land_Flush_Light_red_F, Land_Flush_Light_green_F? This is a runway lights and was not provided in BI objects list.
If not, is there a way to add such objects not to custom compositions but to object list manually?

**Comment by oOKexOo** [comment]
It's actually very easy to be achieved with an add-on. You just have to set the attribute "scopeCurator = 2;" for each object and I actually did it once for a few objects.
However, the problem is that the mission becomes dependent on the add-on if you place such an object in Eden. So I decided to no longer do it.

**Comment by unhappytroll** [comment]
I see.
