### ISSUE TITLE
IED/Suicide Bomber Module Bugs & Questions

### ISSUE THREAD

**Issue by Snak3Doc** [oOKexOo/AresModAchillesExpansion#97]
Updated bugs

Running:
ACE3
CBA
Achilles

First off thank you CreepPork and Kex it's awesome and the fact you can put it on vehicles even better but i have a couple of bugs and questions.

Bugs
- Fake Explosion still causes ACE3 player damage w/IED and suicide bomber (not sure if this is intended)

- Disabling Explosion (well it's a missile, not an explosion and it always flys north?) and I've watched the missile hit the vehicle multiple times and it's caused no damage at all other times its just flies over the top of it and lands a few hundred metres away. and when used on suicide bombers its doesn't seem to be any different than deadly.
(my suggestion would be to use a normal explosion and then remove the damage event handlers, then apply custom damage to vehicle modules, a simple way would be to damage the engine, but if it's possible a randomiser to pull 2 or 3 random modules from a pool to damage would be great(for players it could break their legs maybe)) 

- Doesn't seem to be much of a difference between small medium and large explosion size, especially small maybe use a grenade explosion for small as it seems to big for the name

Q1: How do you set up and use manual triggers?
Q2: How do you set up and use radio triggers?
Q3: (I might be dreaming this) Is it possible to add the directional explosion that options that MCC had.

**Comment by CreepPork** [comment]
@Snak3Doc 1. The fake explosion is a smallest explosion, the one that appears when a vehicle is already destroyed and a new explosion appears, AFAIK it's going to cause at least some kind of damage. That's more up to ACE3 Medical, if you are experiencing issues with it.

2. The disabling explosion is a AT rocket, by classname called M_AT and if it has no impact point it will always fly. It is possible, dunno if it will work, but set a direction to the rocket so it can fly in the way of the object is pointing. Maybe that could be useful, maybe not.

3. The explosion size is used only by the Deadly and Disabling type. For all other types it ignored. For deadly there will be a increase of the charge used. For deadly, small will be the explosive charge, medium, the small IED and for the large, a large IED will spawn. Disabling only increases the damage caused by the rocket.

Q1 & Q2: Check the wiki in this GitHub repo, I added a new page with all the information required.
Q3: Is the current setup not working for you, with directional?
